### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by Spartwo**
allow plugin folder inclusion into the gamedata source, people keep downloading from there.

### CODE REVIEW

**Comment by Halbann** [comment]
I think the problem is that people are trying to download the source rather than the most recent release. Even if the binary for the most recent commit was included in the source, we wouldn't want people to download it instead of the most recent release. Maybe GameData should go inside the Source folder so it doesn't get easily mistaken for a build.

**Comment by Halbann** [comment]
As far as I can tell, none of these mods include up-to-date binaries in their repos, even if they do contain the build's folder structure. Most likely because they don't want people downloading potentially different or non-functional versions of the mod.

https://github.com/BrettRyland/BDArmory
https://github.com/LGhassen/Scatterer
https://github.com/LGhassen/EnvironmentalVisualEnhancements
https://github.com/MuMech/MechJeb2

**Comment by Spartwo** [comment]
> I think the problem is that people are trying to download the source rather than the most recent release. Even if the binary for the most recent commit was included in the source, we wouldn't want people to download it instead of the most recent release. Maybe GameData should go inside the Source folder so it doesn't get easily mistaken for a build.

Want? No.

Will they? Yes

**Comment by Halbann** [comment]
I'm going to move GameData into Source then if you don't have a problem with that.

**Pull request closed without merging**
